stages:
  - install
  - test
  - build
  - migrate
  - deploy

variables:
  BUN_INSTALL_CACHE_DIR: .bun-cache

default:
  image: oven/bun:latest

cache:
  key:
    files:
      - bun.lockb
  paths:
    - .bun-cache/

install:
  stage: install
  script:
    - bun install --frozen-lockfile --prefer-offline
  artifacts:
    paths:
      - node_modules/
      - bun.lockb
    expire_in: 2 hours
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

test:
  stage: test
  script:
    - bun run lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

build:
  stage: build
  script:
    - bun add -g vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
  artifacts:
    paths:
      - .vercel/output/
    expire_in: 2 hours
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

migrate:
  stage: migrate
  script:
    - bun run db:migrate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  script:
    - bun add -g vercel
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
