stages:
  - install
  - test
  - build
  - migrate
  - deploy

variables:
  BUN_INSTALL_CACHE_DIR: .bun-cache

default:
  image: oven/bun:latest
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

.cache:
  cache:
    key:
      files:
        - bun.lockb
    paths:
      - .bun-cache/

install:
  stage: install
  extends: .cache
  script:
    - bun install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - bun.lockb
    expire_in: 2 hours
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'

test:
  stage: test
  extends: .cache
  needs:
    - job: install
      artifacts: true
  script:
    - bun run lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'

build:
  stage: build
  extends: .cache
  needs:
    - job: install
      artifacts: true
  script:
    - bun add -g vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
  artifacts:
    paths:
      - .vercel/
      - node_modules/
    expire_in: 2 hours
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

migrate:
  stage: migrate
  extends: .cache
  needs:
    - job: install
      artifacts: true
    - job: build
      artifacts: true
  script:
    - bun run db:migrate:ci
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  extends: .cache
  interruptible: false
  needs:
    - job: build
      artifacts: true
    - job: migrate
  script:
    - bun add -g vercel
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
